### ISSUE TITLE
expandPath

### ISSUE THREAD

**Issue by ianosullivan** [foundeo/cfdocs#1121]
ACF can incorrectly expand some absolute paths

**Comment by shaedrich** [comment]
Do you have examples?

**Comment by ianosullivan** [comment]
Sure. See here - https://take.ms/zvsrl
`<cfscript>
writeDump( 
	expandPath('C:\ColdFusion2018\cfusion\wwwroot\file_server\fdi_crm\fdicrm000001\cobh tidy towns.png') 
);
</cfscript>`

**Comment by ianosullivan** [comment]
`

`

**Comment by shaedrich** [comment]
The function expects the path which is passed in to be _relative_. If you pass in a _wrong_ path, the result will of course be _wrong_ as well.

**Comment by ianosullivan** [comment]
But as the docs say it also accepts an absolute so i would have thought a
warning about that flaw should be noted.

Ian

**Comment by KamasamaK** [comment]
A distinction should be made between web paths and physical (or as the docs call it "platform-appropriate") paths. You can pass an absolute web path (e.g. one starting with `/`) and it would resolve based on the web root. This would be the same regardless of where in the application it's executed, which is why it is called absolute. A relative web path would resolve the path based on the current directory. This function resolves either of these web path types into the absolute physical path.

**Comment by shaedrich** [comment]
If you enter an absolute web path, it returns something like "C:\home\cflive.net\code\http:\google.com\?s=sdnbv" in acf, but in Lucee it'll be the exact same path you passed in.

**Comment by KamasamaK** [comment]
@shaedrich Good point. The term "absolute web path" alone is not sufficient, because it can often mean the full URL. I am seeing inconsistent usage in the terminology. Some places appear to include those paths that are resolved with respect to the web root as absolute (which is how I was referring to them), but some others call it relative. So instead of using the ambiguous terminology, it would probably be best to just describe what is supported.
