### ISSUE TITLE
queryExecute

### ISSUE THREAD

**Issue by derrick13** [foundeo/cfdocs#273]
The Lucee Link doesn't work

**Comment by mjhagen** [comment]
There is no Lucee documentation for that function as far as I can tell. See: https://luceeserver.atlassian.net/browse/LD-71

**Comment by pfreitag** [comment]
My thought it to keep the link in place because lucee does support the function and when they do add it, the url will be correct. Sound ok? No sense in removing it only to add it back a few weeks later... 

If you wouldn't mind please vote for the issue that @mjhagen referenced, that might get it done faster.

**Comment by derrick13** [comment]
Yes Pete, this definitely makes sense.
I noticed that you already created a Lucee docs issue for queryExecute – so this cfdocs issue doesn’t make sense.
Sorry for adding this issue

-Harry

Von: Pete Freitag [mailto:notifications@github.com]
Gesendet: Montag, 25. Januar 2016 16:20
An: foundeo/cfdocs <cfdocs@noreply.github.com>
Cc: Harry Klein <Klein@contens.de>
Betreff: Re: [cfdocs] queryExecute (#273)


My thought it to keep the link in place because lucee does support the function and when they do add it, the url will be correct. Sound ok? No sense in removing it only to add it back a few weeks later...

If you wouldn't mind please vote for the issue that @mjhagen<https://github.com/mjhagen> referenced, that might get it done faster.

**Comment by pfreitag** [comment]
No worries @derrick13 have a good week!
