### ISSUE TITLE
Param values in JSON

### ISSUE THREAD

**Issue by KamasamaK** [foundeo/cfdocs#489]
What is the meaning of the `values` array in the `params` objects? I assume it is to list the enumerated valid values for instances where those exist. However, I have seen it also used to just give examples.

A good example of this is the [dateDiff function](https://cfdocs.org/datediff). It lists all of the valid values for the `datepart`. It also lists `now()` as a value for both `date1` and `date2`.

**Comment by ddspringle** [comment]
@pfreitag can comment on this more, but from my perspective the `values` array for `params` should only ever be used to enumerate possible values for params that expect them, and not to provide example values.

**Comment by pfreitag** [comment]
Yes it _should_ be used to list the valid possible values when there is a finite list of valid values for an attribute or argument. For example with the `replace()` function the `scope` can be either `all` or `one` nothing else. 

Practically speaking the `values` array is also used to populate autocomplete suggestions for IDE's such as Sublime Text. That is probably why `now()` ended up in there, because it is handy... Technically it probably should be removed.

**Comment by KamasamaK** [comment]
Thanks for confirming this. I don't think its use in autocompletion should influence its use in docs. You could add another key to the JSON for that purpose if it's seen as value. Alternatively, they could look at the param's `type` and just always provide `now()` as an autocomplete suggestion for `DateTime`.

**Comment by pfreitag** [comment]
Yes, I agree - if you want to remove `now()` from `dateDiff` feel free to send a PR and I'll approve it.

**Comment by KamasamaK** [comment]
For this use case, there now exists a property on the param called `suggestions`.
