### ISSUE TITLE
script and tag syntax splitted into two docs

### ISSUE THREAD

**Issue by shaedrich** [foundeo/cfdocs#615]
I guess, that was inadvertently done: There are two docs concerning the same functionality — dump.

- [cfdump](http://cfdocs.org/cfdump)
- [writeDump](http://cfdocs.org/writeDump)

That is redundant and these two would have to be updated simultaneously every time when one was modified to keep both up to date. Not a well practicable approach...

In my opinion we should just keep "cfdump" which have *tag based* and *script based* examples and redirect "writeDump" to it.

If there should be two docs there should a way to link in `function syntax` and `tag syntax` instead of passing the syntax itself which would be redundant.

**Comment by shaedrich** [comment]
That's not the case for [cfsavecontent](http://cfdocs.org/cfsavecontent). But [cfmail](http://cfdocs.org/cfmail) links to it netherless for whatever reason. Should it simply be redirected as the hash "[f](http://cfdocs.org/f)" does to [functions](http://cfdocs.org/functions)?

**Comment by pfreitag** [comment]
I see your point here, but I don't want to loose the metadata about writeDump since it is a proper function (eg it was added in CF9). The order of arguments is important for a function, and not so much for a tag. I definitely don't want to duplicate the docs for things like `<cfhttp>` and `cfhttp();` since those are _tag to script equivalents_  

I am going to close this issue. I am ok with the duplication as long as it is a proper function (eg it is defined in `getFunctionList()`)

**Comment by shaedrich** [comment]
So we could add a key for that to show a notice? We also could update some keys when they are changed in the other doc.
